# -*- coding: utf-8 -*-
"""main_FB_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1af1-AwLdmw_lgd2ZU5A_LnBQx-ZCq78t
"""

import firebase_admin
from firebase_admin import credentials, db
import pickle
import numpy as np
import time
import warnings
warnings.filterwarnings("ignore")

print("starting ML Engine..")

model = pickle.load(open('health_status_model.pkl', 'rb'))
scaler = pickle.load(open('scaler.pkl', 'rb'))
print("Model & Scaler Loaded")

cred = credentials.Certificate("moeenapp-9a886-firebase-adminsdk-fbsvc-6d7264054b.json")
firebase_admin.initialize_app(cred, {
    'databaseURL': 'https://moeenapp-9a886-default-rtdb.firebaseio.com/'
})
print("Firebase Running")

"""Load model & scaler"""

input_ref = db.reference('/sensorData')
pred_ref = db.reference('/Predections')

"""Main Loop"""

def combined_predections(pulse, temp, spo2):
  if pulse < 60 or pulse > 110:
    return 1, "Abnormal"

  if temp < 36 or temp > 38:
    return 1, "Abnormal"

  if spo2 < 95:
    return 1, "Abnormal"

  X = np.array([[pulse, temp, spo2]])
  X_scaled = scaler.transform(X)
  pred = int(model.predict(X_scaled)[0])

  if pred ==0:
    result = "Normal"
  else:
    result = "Abnormal"


  return pred, result

from re import X
def classify_health():
  data = input_ref.get()

  if data is None:
      print("No data available")
      return

  pulse =data.get("heartRate", 0)
  temp = data.get("temperature")
  spo2 = data.get("spo2")

  if pulse is None or temp is None or spo2 is None:
    print("missing fields")
    return

  pulse = float(pulse)
  temp = float(temp)
  spo2 = float(spo2)

  prediction, result = combined_predections(pulse, temp, spo2)

# result = "Normal" if prediction == 0 else "Abnormal"

  pred_ref.set({
        "predection": int(prediction),
        "HealthStatus": result,
        "heartRate": pulse,
        "temperature": temp,
        "spo2": spo2
    })

def listener(event):
  print("New sensor data:", event.data)
  classify_health()

input_ref.listen(listener)